config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :dashboard_forms
  resources :information_forms
  devise_for :admins, controllers: {registrations: "admins/registrations"}
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/dashboard_forms', to: 'dashboard_forms#index', as: :form_for_admin
  get '/information_forms', to: 'information_forms#index', as: :form_for_user
  # Defines the root path route ("/")
  get "about", to: "pages#about", as: :about
  get "show_admin_users", to: 'pages#show_admin_users', as: :show_admin_users
  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'dashboard_forms#index', as: :admin_root
end

app/views/admin/primary.html.erb
<div class="primary">
  <h2 class="Title">Hey Mum!</h2>
  <h5>This is your dashboard for the Bosham Oil Syndicate *BOS*. Please select the button below and go to your company creator page. Once you have completed the form, you will be taken to the the Meeting Room.</h5>
  <h5>At the very bottom of the page. </h5>
  <h5>As updates are made to this site, key parts are likely to change, including a reset of the comment table every 24 hours and more interactive features.</h5>
  <%= link_to "Company Input page", form_for_admin_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>