config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :dashboard_forms
  resources :information_forms
  devise_for :admins, controllers: {registrations: "admins/registrations"}
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/dashboard_forms', to: 'dashboard_forms#index', as: :form_for_admin
  get '/information_forms', to: 'information_forms#index', as: :form_for_user
  # Defines the root path route ("/")
  get "about", to: "pages#about", as: :about
  get "show_admin_users", to: 'pages#show_admin_users', as: :show_admin_users
  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'dashboard_forms#index', as: :admin_root
end

app/controllers/information_forms_controller.rb
class InformationFormsController < ApplicationController
  before_action :set_information_form, only: %i[ show edit update destroy ]

  def index
    if current_user.admin?
      @information_form = InformationForm.all
    else
      @information_forms = InformationForm.where(user: current_user)
    end
  end

  def show
    if current_user.admin?
      @information_forms = InformationForm.all
    else
      @information_forms = InformationForm.where(user: current_user)
    end
  end

  def new
    @information_form = InformationForm.new
  end

  def edit
  end

  def create

    @information_form = InformationForm.new(information_form_params)
    @information_form.user = current_user

    respond_to do |format|
      if @information_form.save
        format.html { redirect_to information_form_url(@information_form), notice: "Your input has been registered." }
        format.json { render :show, status: :created, location: @information_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @information_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information_forms/1 or /information_forms/1.json
  def update
    respond_to do |format|
      if @information_form.update(information_form_params)
        format.html { redirect_to information_form_url(@information_form), notice: "Information form was successfully updated." }
        format.json { render :show, status: :ok, location: @information_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @information_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information_forms/1 or /information_forms/1.json
  def destroy
    @information_form.destroy

    respond_to do |format|
      format.html { redirect_to information_forms_url, notice: "Information form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information_form
      @information_form = InformationForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def information_form_params
      params.require(:information_form).permit(:name, :address, :fuel_needed, :phone_number, :instructions_for_delivery, :comment)
    end
end

app/views/information_forms/_form.html.erb
<%= simple_form_for(@information_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :fuel_needed %>
    <%= f.input :phone_number %>
    <%= f.input :instructions_for_delivery %>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
  </div>
<% end %>
<br>

app/views/information_forms/_information_form.html.erb
<div id="<%= dom_id information_form %>" class="my-info">
  <p>
    <strong>Name:</strong>
    <%= information_form.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= information_form.address %>
  </p>

  <p>
    <strong>Fuel needed:</strong>
    <%= information_form.fuel_needed %>l
  </p>

  <p>
    <strong>phone_number:</strong>
    <%= information_form.phone_number %>
  </p>

  <p>
    <strong>delivery Info:</strong>
    <%= information_form.instructions_for_delivery %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= information_form.comment %>
  </p>

</div>

app/views/information_forms/edit.html.erb
<div class="background3">
  <div class="inform">
    <h3>Please make any/all necessary edits</h3>

    <%= render "form", information_form: @information_form %>

    <br>

    <div class="button-edit">
      <%= link_to "Cancel information input", information_forms_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    </div>
  </div>
</div>

app/views/information_forms/index.html.erb
<%# <p style="color: green"><%= notice %>
<div class="background3">
  <div class="inform">
    <h1>My Information:</h1><br>
      <div id="information_forms">
        <div class="my-info">
          <% @information_forms.each do |information_form| %>
            <%= render information_form %>
        </div>
          <%= link_to "Edit My information", information_form, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
      <% end %>
    </div>
    <% if @information_forms.count == 1 %>
    <% else %>
      <strong><%= link_to "Create your fuel form", new_information_form_path, :class => "create-new" %></strong><br><br>
    <% end %>
    <%= link_to "Back to the Main Page", user_registration_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    <% if @information_forms.count == 1 %>
      <br><br><p>* Your information has been sent to the sites administrator. Feel free to update it when ever necessary.</p>
    <% end %>
    </div>
</div>

app/views/information_forms/new.html.erb
<div class="background3">
  <div class="inform">
    <h1>Please fill in all boxes: </h1>

    <%= render "form", information_form: @information_form %>

    <br>

    <div class="return">
      <%= link_to "Go back", information_forms_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    </div>
  </div>
</div>

app/views/information_forms/show.html.erb
<div class="background3">
  <div class="inform">
    <div class="fillout">
      <%= render @information_form %>
    </div>

      <div class="user-butt">
        <%= link_to "Edit my information", edit_information_form_path(@information_form), class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %><br>
        <%= link_to "Back to My Dashboard", information_forms_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
        <%= button_to "Reset information", @information_form, method: :delete, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
      </div>
  </div>
</div>