config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :dashboard_forms
  resources :information_forms
  devise_for :admins, controllers: {registrations: "admins/registrations"}
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/dashboard_forms', to: 'dashboard_forms#index', as: :form_for_admin
  get '/information_forms', to: 'information_forms#index', as: :form_for_user
  # Defines the root path route ("/")
  get "about", to: "pages#about", as: :about
  get "show_admin_users", to: 'pages#show_admin_users', as: :show_admin_users
  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'dashboard_forms#index', as: :admin_root
end

app/views/pages/about.html.erb
<div class="background2">
<br><br><br><br><br><br><br><br>
  <div class="blur">
    <div class="box6">
      <div class="what">
        <h1><strong>About</strong></h1>
        <h4>Welcome to the BOS Bosham Oil Syndicate!</h4>
      </div>
      <p>This website is for property owners in the Bosham area that require imported oil. Through the Bosham Oil Syndicate, administrated by Mrs Racheal Murphy, the website is tasked with providing the admin information on syndicate members key information, primarily their fuel cap and oil requirements. Once all oil requirements are collected, the administrator will assess various oil distributors to collect the necessary quantity of oil.</p>

      <div class="homage">
        <%= link_to "Back to the Home Page", root_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <%# <link rel="stylesheet" href="components/_index.scss" /> %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Website Homepage</title>
</head>
<div class="background2">
  <% if current_user.present? == false %>
  <br>
    <div class="index">
      <div class="bulky">
        <div class="intro_box">
          <div class="logo col-12 col-lg-6">
            <%= image_tag 'the_official_bos.png', class: "logo" %>
            <div class="m-8" ><h1 class="text-center-logo"><strong>The<br> BOS</strong></h1></div>
          </div>
        </div>
          <h3>Please select if you are a returning user, new user or the administrator</h3>
          <br>
          <div class="about">
            <%= link_to "About the site", about_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
          </div>
      </div>
        <div class="which_root">
                  <div class="alignment">
                      <div class="user col-5">
                        <%= link_to "User", user_session_path( status: { status:"user" }), class: "btn btn-pink text-grey text-uppercase fw-bold", style: "color:black"%>
                      </div>
                      <div class="admin col-5">
                        <%= link_to "admin", admin_session_path( status: { status:"admin" }), class: "btn btn-pink text-grey text-uppercase fw-bold", style: "color:black" %>
                      </div><br>
                      <div class="user col-5">
                        <%= link_to "New User", new_user_registration_path( status: { status:"user" }), class: "btn btn-pink text-grey text-uppercase fw-bold", style: "color:black"%>
                      </div>
                  </div>
        </div>
    </div>
    <% end %>
</div>

app/views/pages/show_admin_users.html.erb
<div class="print">
  <div class="printable">
    <table>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Fuel Needed</th>
        <th>Phone Number</th>
        <th>Fuel Directions</th>

      </tr>
      <% InformationForm.all.each do |form| %>
        <tr>
          <td><%= form.name %></td>
          <td><%= form.address %></td>
          <td><%= form.fuel_needed %>l</td>
          <td><%= form.phone_number %></td>
          <td><%= form.instructions_for_delivery %></td>
          <%# <td><%= form.comment %>
        </tr>
      <% end %>
    </table>

  </div>

<br>
  <div class="big_number_print">
    <h3><strong>Fuel Needed: </strong></h3>
    <div class="collective"><%= InformationForm.all.sum(:fuel_needed) %> litres</div>
  </div>
  <button onclick="window.print()">Print this page</button>
</div>