config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :dashboard_forms
  resources :information_forms
  devise_for :admins, controllers: {registrations: "admins/registrations"}
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/dashboard_forms', to: 'dashboard_forms#index', as: :form_for_admin
  get '/information_forms', to: 'information_forms#index', as: :form_for_user
  # Defines the root path route ("/")
  get "about", to: "pages#about", as: :about
  get "show_admin_users", to: 'pages#show_admin_users', as: :show_admin_users
  get 'users' => 'users#primary', as: :user_root
  get 'admins' => 'dashboard_forms#index', as: :admin_root
end

app/controllers/dashboard_forms_controller.rb
class DashboardFormsController < ApplicationController
  before_action :set_dashboard_form, only: %i[ show edit update destroy ]

  # GET /dashboard_forms or /dashboard_forms.json
  def index
    @dashboard_forms = DashboardForm.all
  end

  # GET /dashboard_forms/1 or /dashboard_forms/1.json
  def show
    @dashboard_forms = DashboardForm.all
  end

  def new
    @dashboard_form = DashboardForm.new
  end

  # GET /dashboard_forms/1/edit
  def edit
  end

  # POST /dashboard_forms or /dashboard_forms.json
  def create
    @dashboard_form = DashboardForm.new(dashboard_form_params)

    respond_to do |format|
      if @dashboard_form.save
        format.html { redirect_to dashboard_form_url(@dashboard_form), notice: "New Company was successfully created." }
        format.json { render :show, status: :created, location: @dashboard_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dashboard_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Dashboard_forms/1 or /Dashboard_forms/1.json
  def update
    respond_to do |format|
      if @dashboard_form.update(dashboard_form_params)
        format.html { redirect_to dashboard_form_url(@dashboard_form), notice: "Company Updated." }
        format.json { render :show, status: :ok, location: @dashboard_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dashboard_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard_forms/1 or /dashboard_forms/1.json
  def destroy
    @dashboard_form.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_forms_url, notice: "Dashboard form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_form
      @dashboard_form = DashboardForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dashboard_form_params
      params.require(:dashboard_form).permit(:company_name, :company_address, :representative_name, :phone_number, :pence_per_litre, :comment, :date_of_call, :rating, :admin_id)
    end
end

app/views/dashboard_forms/_dashboard_form.html.erb
<div class="box">
  <div class="cube">
    <div class="card">
      <div id="<%= dom_id dashboard_form %>">
        <%# <p> %>
          <%# <strong>Company name:</strong> %>
          <%= dashboard_form.company_name %> <br>
        <%# </p> %>

        <%# <p> %>
          <%# <strong>Representative Name:</strong> %>
          <%= dashboard_form.representative_name %> <br>
        <%# </p> %>

        <%# <p> %>
          <%# <strong>Phone number:</strong> %>
          <%= dashboard_form.phone_number %> <br>
        <%# </p> %>

        <%# <p> %>
          <%# <strong>Pence per litre:</strong> %>
          <%= dashboard_form.pence_per_litre %>p <br>
        <%# </p> %>

        <%# <p> %>
          <%# <strong>Date of Call:</strong> %>
          <%= dashboard_form.date_of_call.strftime('%D') %> <br>
        <%# </p> %>

        <%# <p> %>
          <%# <strong>Comment:</strong> %>
          <%= dashboard_form.comment %> <br>
        <%# </p> %>

      </div>
      <%= link_to "More info", dashboard_form, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    </div>
  </div>
</div>

app/views/dashboard_forms/_form.html.erb
<%= simple_form_for(@dashboard_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="area1">
      <div class="col-5">
        <%= f.input :company_name %>
      </div>
      <div class="col-5">
        <%= f.input :company_address %>
      </div>
    </div>
    <div class="area1">
      <div class="col-5">
        <%= f.input :representative_name %>
      </div>
      <div class="col-5">
        <%= f.input :phone_number %>
      </div>
    </div>
    <div class="area1">
      <div class="col-5">
        <%= f.input :pence_per_litre %>
      </div>
      <div class="col-5">
        <%= f.input :comment %>
      </div>
    </div>
    <div class="timing col-10">
      <%= f.input :date_of_call%>
    </div>
    <div class="area1">
      <div class="col-5">
        <%= f.input :rating %>
      </div>
      <%# <div class="col-5"> %>
        <%# <%= f.association :admin %>
      <%# </div> %>
  </div>

  <div class="form-actions col-6">
    <%= f.button :submit, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
  </div>
<% end %>

app/views/dashboard_forms/edit.html.erb
<div class="entirity">
  <div class="inform2">
    <div class="title2"><h1>Editing Company</h1></div>
      <%= render "form", dashboard_form: @dashboard_form %>
      <div class="central"><br>
        <%= link_to "Back to your dashboard", dashboard_forms_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard_forms/index.html.erb
<div class="entirity">
  <div class="middle">
    <div class="row-primary">
    <div class="rows">
          <div class="row2 col-5">
              <div class="card3">
                <div class="demand2">demand</div>
                <div class="card4">
                  <div class="what"><strong>Name: </strong></div>
                  <% InformationForm.all.each do |form|%>
                    <%= form.name%><br>
                  <% end %>
                </div>
                <div class="card5">
                  <div class="what"><strong>Fuel Requested</strong></div>
                  <% InformationForm.all.each do |form|%>
                  <%= form.fuel_needed %>l<br>
                  <% end %>
                </div>
                <div class="card6">
                  <div class="what"><strong>Comments</strong></div>
                  <% InformationForm.all.each do |form|%>
                    <div class="hoverinfo"> <span class="dispatch">comment</span>
                      <p><%= form.comment %></p>
                    </div>
                  <% end %>
                </div>
              </div>
              </div>

            </div>
          <%# <div class="container2 col-8"> %>
          <%# <div class="row"> %>
            <%# <div class="card-key col-5"> %>

              <%# <div id="dashboard_forms" class="scroll"> %>
                <%# <% @dashboard_forms.each do |dashboard_form| %>
                  <%# <%= render dashboard_form %>
                <%# <% end %>
              <%# </div> %>
            <%# </div> %>
          <%# </div> %>
          <%# <div class="container2 col-8"> %>
            <div class="row">
                  <%# SUPPLY RIGHT, DEMAND LEFT!!!!!!!! %>

              <div class="bigcard">
                <div class="demand">supply</div>
                    <div class="officialcard">
                      <strong>Name:</strong> <br>
                      <% DashboardForm.all.each do |form|%>
                        <%= form.company_name%><br>
                      <% end %>
                    </div>
                    <div class="officialcard1">
                      <strong>Rep.</strong><br>
                      <% DashboardForm.all.each do |form|%>
                      <%= form.representative_name %><br>
                      <% end %>
                    </div>
                    <div class="officialcard2">
                      <strong>Phone No.</strong> <br>
                      <% DashboardForm.all.each do |form|%>
                      <%= form.phone_number %><br>
                      <% end %>
                    </div>
                    <div class="officialcard3">
                      <strong>Price</strong> <br>
                      <% DashboardForm.all.each do |form|%>
                      <%= form.pence_per_litre %>p<br>
                      <% end %>
                    </div>
                    <div class="officialcard4">
                      <strong>Last call</strong> <br>
                      <% DashboardForm.all.each do |form|%>
                      <%= form.date_of_call.strftime('%D') %><br>
                      <% end %>
                    </div>
                    <div class="officialcard5">
                      <strong> </strong> <br>
                      <% DashboardForm.all.each do |form|%>
                        <div class="hoverinfo"> <span class="dispatch">comment</span>
                          <p><%= form.comment %></p>
                        </div>
                      <% end %>
                    </div>
                    <div class="officialcard6">
                      <strong> </strong> <br>
                      <% DashboardForm.all.each do |form|%>
                      <%= link_to "Edit", edit_dashboard_form_path(form), class: "text-decoration-none" %><br>
                      <% end %>
                    </div>
                  </div>
            <div class="conclusion">
                <div class="title col-4">
                  <div class="cool">
                    <%= image_tag 'the_official_bos.png', class: "logo" %>
                    <div class="central"><%= link_to "Log out", destroy_admin_session_path, data: {turbo_method: :delete}, class: "btn btn-pink text-light text-uppercase rounded-pill fw-bold py-2 px-3", style: "black" %></div></div><br>
                  </div>
                  <div class="big_number">
                    <h3><strong>Fuel Needed: </strong></h3>
                    <div class="bob"><%= InformationForm.all.sum(:fuel_needed) %> litres</div>
                  </div>
                  <div class="key_buttons">
                  <div class="create_new"><%= link_to "Create Supplier", new_dashboard_form_path, class: "btn btn-pink text-black text-uppercase rounded-pill fw-bold py-3 px-5" %></div>
                  <div class="btn btn-pink text-black text-uppercase rounded-pill fw-bold py-3 px-5"><a href="mailto: <%= User.pluck(:email).join(',') %>", class="email_link"><strong>Email Syndicators</strong></a></div>
                  <div class="about">
                  <%= link_to "Print User Information", show_admin_users_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
          </div>
                  </div>
                </div>

              </div>

            </div>
        <%# </div> %>
        <%# THIS WORKS=> <button onclick="window.print()">Print this page</button> %>
</div>
    </div>
  </div>
</div>

app/views/dashboard_forms/new.html.erb
<div class="entirity">
  <div class="inform2">
    <div class="title2"><h1>New Company</h1></div>

    <%= render "form", dashboard_form: @dashboard_form %>


    <div class="form-actions col-6">
      <%= link_to "Cancel Company", dashboard_forms_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
    </div>
  </div>
</div>

app/views/dashboard_forms/show.html.erb
<div class="entirity">
  <div class="inform">
    <div class="edit-style">
      <div class="edition">
        <%= render @dashboard_form %>
      </div>

      <div class="edit-options">
        <br>
        <%= link_to "Edit company information", edit_dashboard_form_path(@dashboard_form), class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %> <br><br>
        <%= link_to "Return to the Dashboard", dashboard_forms_path, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %> <br><br>

        <%= button_to "Delete company", @dashboard_form, method: :delete, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>
      </div>
    </div>
  </div>
</div>